# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Son Et Lumiere
email: sean.contenti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Son et lumiere, sound and light. Shedding light on geophysics geology, and geocomputing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sconten.github.io" # the base hostname & protocol for your site
twitter_username: sconten
github_username:  sconten

# Build settings
markdown: kramdown
